"""
Letter of Intent (LOI) generator powered by Groq (LLaMA 3.3 70B).

Produces professional, persuasive LOI prose tailored to a specific
grant opportunity and nonprofit organization profile.
"""

import asyncio
import logging
import os
from datetime import datetime, timezone

from groq import Groq

logger = logging.getLogger(__name__)

# ── Groq client ──────────────────────────────────────────────────────────────
client = Groq(api_key=os.environ["GROQ_API_KEY"])

MODEL = "llama-3.3-70b-versatile"

# ── LOI prompt template ─────────────────────────────────────────────────────
LOI_PROMPT = """\
You are an expert grant writer with 20+ years of experience writing \
successful Letters of Intent for nonprofit advocacy organizations. You have \
a proven track record of securing funding from major foundations and \
government agencies.

Write a complete, polished Letter of Intent for the following grant \
opportunity on behalf of the organization described below. \
Use the match analysis provided to strengthen the narrative.

ORGANIZATION PROFILE:
- Name: {org_name}
- Mission: {org_mission}
- Focus Areas: {org_focus_areas}
- Location: {org_location}
- Annual Budget Range: {org_budget}

GRANT OPPORTUNITY:
- Title: {grant_title}
- Funder: {grant_funder}
- Description: {grant_description}
- Deadline: {grant_deadline}
- Maximum Award: {grant_max_amount}

MATCH ANALYSIS (use this to strengthen the narrative):
- Why this is a good fit: {match_reasoning}
- Alignment strengths: {alignment_strengths}
- Potential concerns to address proactively: {concerns}

STRUCTURE YOUR LOI AS FOLLOWS:

1. LETTERHEAD BLOCK — Organization name, today's date ({today_date}), and \
a formal header. Use the actual organization name and date provided above.

2. SALUTATION — Address the letter to the grants team at {grant_funder}. \
Use "Dear {grant_funder} Grants Review Committee" as the salutation.

3. OPENING PARAGRAPH — State the purpose of this letter: to express intent \
to apply for the {grant_title}. Explain why {grant_funder} is the ideal \
funding partner for this work. Make this compelling and specific.

4. THE NEED — Describe the problem the organization addresses. Ground this \
in the organization's mission. Use confident, data-aware language that \
conveys expertise and urgency.

5. THE FIT — Directly reference the alignment strengths from the match \
analysis. Explain why this organization is uniquely positioned to deliver \
on the grant's objectives. Address any concerns from the match analysis \
proactively and tactfully.

6. THE IMPACT — Describe what will be achieved with this funding. Be \
specific about outcomes, communities served, and measurable goals. Paint \
a vivid picture of success.

7. CLOSING — Include a clear funding ask (reference the maximum award \
amount if available), express enthusiasm for partnership, and provide a \
call to action (offer to discuss further, submit a full proposal, etc.). \
Sign off with the organization name.

CRITICAL RULES:
- Write flowing, professional prose. Do NOT use bracketed placeholders \
like [Insert Name] or [Add details here]. If any value is missing or says \
"Not specified", write around it naturally without drawing attention to it.
- Tone: Confident, respectful, and urgent. This should read like it was \
written by a seasoned development director, not generated by AI.
- Length: 600-900 words. Comprehensive but concise.
- Format: Use clean markdown with appropriate headers.
"""


async def generate_loi(org: dict, grant: dict, match_reasoning: dict) -> str:
    """
    Generate a professional Letter of Intent using Groq (LLaMA 3.3 70B).

    Args:
        org: Organization profile with name, mission, focus_areas,
             location, budget_range.
        grant: Grant details with title, funder, description,
               deadline, max_amount.
        match_reasoning: Match analysis with reasoning,
                         alignment_strengths, concerns.

    Returns:
        Markdown-formatted LOI text, or a fallback message on failure.
    """
    try:
        # ── Format values with graceful fallbacks ────────────────────
        deadline_raw = grant.get("deadline")
        if isinstance(deadline_raw, datetime):
            deadline_str = deadline_raw.strftime("%B %d, %Y")
        elif deadline_raw:
            deadline_str = str(deadline_raw)
        else:
            deadline_str = "Rolling / Not specified"

        max_amount_raw = grant.get("max_amount")
        if max_amount_raw is not None:
            max_amount_str = f"${max_amount_raw:,.0f}"
        else:
            max_amount_str = "Not specified"

        focus_areas = org.get("focus_areas") or ["community impact"]
        strengths = match_reasoning.get("alignment_strengths") or []
        concerns = match_reasoning.get("concerns") or []

        prompt = LOI_PROMPT.format(
            org_name=org.get("name", "Our Organization"),
            org_mission=org.get("mission", "Advancing community well-being"),
            org_focus_areas=", ".join(focus_areas),
            org_location=org.get("location", "United States"),
            org_budget=org.get("budget_range", "Not specified"),
            grant_title=grant.get("title", "this funding opportunity"),
            grant_funder=grant.get("funder", "the Foundation"),
            grant_description=grant.get("description", "")[:2000],
            grant_deadline=deadline_str,
            grant_max_amount=max_amount_str,
            match_reasoning=match_reasoning.get("reasoning", "Strong mission alignment"),
            alignment_strengths=", ".join(strengths) if strengths else "Direct mission alignment",
            concerns=", ".join(concerns) if concerns else "None identified",
            today_date=datetime.now(timezone.utc).strftime("%B %d, %Y"),
        )

        response = await asyncio.to_thread(
            client.chat.completions.create,
            model=MODEL,
            messages=[{"role": "user", "content": prompt}],
        )
        return response.choices[0].message.content

    except Exception as exc:
        logger.error("LOI generation failed: %s", exc)
        return "LOI generation failed. Please try again."
